# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "ab82f122718af01befbc08e3e96cc8c1"
name = "Cracktab - SEO Booster"
handle = "seo-booster-ai"
application_url = "http://localhost:3000/app"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products,write_products,read_content,write_content,read_themes,write_themes,read_metaobjects,write_metaobjects,read_files,write_files,write_draft_orders,read_draft_orders,write_orders,read_orders"

[auth]
redirect_urls = [
  "http://localhost:3000/auth/callback",
  "http://localhost:3000/auth/shopify/callback",
  "http://localhost:3000/api/auth/callback"
]

[app_proxy]
url = "http://localhost:3000/cod"
subpath = "cod-checkout"
prefix = "apps"

[webhooks]
api_version = "2024-07"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "creatorhandcrafts.myshopify.com"
